/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterestsRouteImport } from './routes/interests'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatsIndexRouteImport } from './routes/chats.index'
import { Route as ProfileScoreRouteImport } from './routes/profile.score'
import { Route as ExploreIdRouteImport } from './routes/explore.$id'
import { Route as ChatsIdRouteImport } from './routes/chats.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsRoute = InterestsRouteImport.update({
  id: '/interests',
  path: '/interests',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileScoreRoute = ProfileScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => ProfileRoute,
} as any)
const ExploreIdRoute = ExploreIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExploreRoute,
} as any)
const ChatsIdRoute = ChatsIdRouteImport.update({
  id: '/chats/$id',
  path: '/chats/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRouteWithChildren
  '/interests': typeof InterestsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/chats/$id': typeof ChatsIdRoute
  '/explore/$id': typeof ExploreIdRoute
  '/profile/score': typeof ProfileScoreRoute
  '/chats/': typeof ChatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRouteWithChildren
  '/interests': typeof InterestsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/chats/$id': typeof ChatsIdRoute
  '/explore/$id': typeof ExploreIdRoute
  '/profile/score': typeof ProfileScoreRoute
  '/chats': typeof ChatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRouteWithChildren
  '/interests': typeof InterestsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/chats/$id': typeof ChatsIdRoute
  '/explore/$id': typeof ExploreIdRoute
  '/profile/score': typeof ProfileScoreRoute
  '/chats/': typeof ChatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/interests'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/chats/$id'
    | '/explore/$id'
    | '/profile/score'
    | '/chats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/interests'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/chats/$id'
    | '/explore/$id'
    | '/profile/score'
    | '/chats'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/explore'
    | '/interests'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/chats/$id'
    | '/explore/$id'
    | '/profile/score'
    | '/chats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  InterestsRoute: typeof InterestsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  ChatsIdRoute: typeof ChatsIdRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests': {
      id: '/interests'
      path: '/interests'
      fullPath: '/interests'
      preLoaderRoute: typeof InterestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/': {
      id: '/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/score': {
      id: '/profile/score'
      path: '/score'
      fullPath: '/profile/score'
      preLoaderRoute: typeof ProfileScoreRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/explore/$id': {
      id: '/explore/$id'
      path: '/$id'
      fullPath: '/explore/$id'
      preLoaderRoute: typeof ExploreIdRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/chats/$id': {
      id: '/chats/$id'
      path: '/chats/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof ChatsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExploreRouteChildren {
  ExploreIdRoute: typeof ExploreIdRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreIdRoute: ExploreIdRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

interface ProfileRouteChildren {
  ProfileScoreRoute: typeof ProfileScoreRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileScoreRoute: ProfileScoreRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRouteWithChildren,
  InterestsRoute: InterestsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  ChatsIdRoute: ChatsIdRoute,
  ChatsIndexRoute: ChatsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
