/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitsManagerRouteImport } from './routes/visits-manager'
import { Route as VisitsRouteImport } from './routes/visits'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as ParaTiRouteImport } from './routes/para-ti'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterestsRouteImport } from './routes/interests'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyListingsIndexRouteImport } from './routes/my-listings.index'
import { Route as ExploreIndexRouteImport } from './routes/explore.index'
import { Route as ChatsIndexRouteImport } from './routes/chats.index'
import { Route as CandidatesIndexRouteImport } from './routes/candidates.index'
import { Route as ProfileScoreRouteImport } from './routes/profile.score'
import { Route as MyListingsNewRouteImport } from './routes/my-listings.new'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as FeedbackMatchIdRouteImport } from './routes/feedback.$matchId'
import { Route as ExploreMapaRouteImport } from './routes/explore.mapa'
import { Route as ExploreIdRouteImport } from './routes/explore.$id'
import { Route as ChatsIdRouteImport } from './routes/chats.$id'
import { Route as CandidatesRequestIdRouteImport } from './routes/candidates.$requestId'

const VisitsManagerRoute = VisitsManagerRouteImport.update({
  id: '/visits-manager',
  path: '/visits-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsRoute = VisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaTiRoute = ParaTiRouteImport.update({
  id: '/para-ti',
  path: '/para-ti',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsRoute = InterestsRouteImport.update({
  id: '/interests',
  path: '/interests',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsIndexRoute = MyListingsIndexRouteImport.update({
  id: '/my-listings/',
  path: '/my-listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIndexRoute = CandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileScoreRoute = ProfileScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => ProfileRoute,
} as any)
const MyListingsNewRoute = MyListingsNewRouteImport.update({
  id: '/my-listings/new',
  path: '/my-listings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackMatchIdRoute = FeedbackMatchIdRouteImport.update({
  id: '/feedback/$matchId',
  path: '/feedback/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreMapaRoute = ExploreMapaRouteImport.update({
  id: '/explore/mapa',
  path: '/explore/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIdRoute = ExploreIdRouteImport.update({
  id: '/explore/$id',
  path: '/explore/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIdRoute = ChatsIdRouteImport.update({
  id: '/chats/$id',
  path: '/chats/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRequestIdRoute = CandidatesRequestIdRouteImport.update({
  id: '/candidates/$requestId',
  path: '/candidates/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/interests': typeof InterestsRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/para-ti': typeof ParaTiRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRouteWithChildren
  '/publish': typeof PublishRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/splash': typeof SplashRoute
  '/visits': typeof VisitsRoute
  '/visits-manager': typeof VisitsManagerRoute
  '/candidates/$requestId': typeof CandidatesRequestIdRoute
  '/chats/$id': typeof ChatsIdRoute
  '/explore/$id': typeof ExploreIdRoute
  '/explore/mapa': typeof ExploreMapaRoute
  '/feedback/$matchId': typeof FeedbackMatchIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/my-listings/new': typeof MyListingsNewRoute
  '/profile/score': typeof ProfileScoreRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/chats/': typeof ChatsIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/my-listings/': typeof MyListingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/interests': typeof InterestsRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/para-ti': typeof ParaTiRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRouteWithChildren
  '/publish': typeof PublishRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/splash': typeof SplashRoute
  '/visits': typeof VisitsRoute
  '/visits-manager': typeof VisitsManagerRoute
  '/candidates/$requestId': typeof CandidatesRequestIdRoute
  '/chats/$id': typeof ChatsIdRoute
  '/explore/$id': typeof ExploreIdRoute
  '/explore/mapa': typeof ExploreMapaRoute
  '/feedback/$matchId': typeof FeedbackMatchIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/my-listings/new': typeof MyListingsNewRoute
  '/profile/score': typeof ProfileScoreRoute
  '/candidates': typeof CandidatesIndexRoute
  '/chats': typeof ChatsIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/my-listings': typeof MyListingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/interests': typeof InterestsRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/para-ti': typeof ParaTiRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRouteWithChildren
  '/publish': typeof PublishRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/splash': typeof SplashRoute
  '/visits': typeof VisitsRoute
  '/visits-manager': typeof VisitsManagerRoute
  '/candidates/$requestId': typeof CandidatesRequestIdRoute
  '/chats/$id': typeof ChatsIdRoute
  '/explore/$id': typeof ExploreIdRoute
  '/explore/mapa': typeof ExploreMapaRoute
  '/feedback/$matchId': typeof FeedbackMatchIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/my-listings/new': typeof MyListingsNewRoute
  '/profile/score': typeof ProfileScoreRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/chats/': typeof ChatsIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/my-listings/': typeof MyListingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/favorites'
    | '/help'
    | '/inbox'
    | '/interests'
    | '/login'
    | '/matches'
    | '/notifications'
    | '/onboarding'
    | '/para-ti'
    | '/preferences'
    | '/profile'
    | '/publish'
    | '/register'
    | '/reset-password'
    | '/rooms'
    | '/settings'
    | '/splash'
    | '/visits'
    | '/visits-manager'
    | '/candidates/$requestId'
    | '/chats/$id'
    | '/explore/$id'
    | '/explore/mapa'
    | '/feedback/$matchId'
    | '/legal/privacy'
    | '/legal/terms'
    | '/my-listings/new'
    | '/profile/score'
    | '/candidates/'
    | '/chats/'
    | '/explore/'
    | '/my-listings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dashboard'
    | '/favorites'
    | '/help'
    | '/inbox'
    | '/interests'
    | '/login'
    | '/matches'
    | '/notifications'
    | '/onboarding'
    | '/para-ti'
    | '/preferences'
    | '/profile'
    | '/publish'
    | '/register'
    | '/reset-password'
    | '/rooms'
    | '/settings'
    | '/splash'
    | '/visits'
    | '/visits-manager'
    | '/candidates/$requestId'
    | '/chats/$id'
    | '/explore/$id'
    | '/explore/mapa'
    | '/feedback/$matchId'
    | '/legal/privacy'
    | '/legal/terms'
    | '/my-listings/new'
    | '/profile/score'
    | '/candidates'
    | '/chats'
    | '/explore'
    | '/my-listings'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/dashboard'
    | '/favorites'
    | '/help'
    | '/inbox'
    | '/interests'
    | '/login'
    | '/matches'
    | '/notifications'
    | '/onboarding'
    | '/para-ti'
    | '/preferences'
    | '/profile'
    | '/publish'
    | '/register'
    | '/reset-password'
    | '/rooms'
    | '/settings'
    | '/splash'
    | '/visits'
    | '/visits-manager'
    | '/candidates/$requestId'
    | '/chats/$id'
    | '/explore/$id'
    | '/explore/mapa'
    | '/feedback/$matchId'
    | '/legal/privacy'
    | '/legal/terms'
    | '/my-listings/new'
    | '/profile/score'
    | '/candidates/'
    | '/chats/'
    | '/explore/'
    | '/my-listings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DashboardRoute: typeof DashboardRoute
  FavoritesRoute: typeof FavoritesRoute
  HelpRoute: typeof HelpRoute
  InboxRoute: typeof InboxRoute
  InterestsRoute: typeof InterestsRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ParaTiRoute: typeof ParaTiRoute
  PreferencesRoute: typeof PreferencesRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  PublishRoute: typeof PublishRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoomsRoute: typeof RoomsRoute
  SettingsRoute: typeof SettingsRoute
  SplashRoute: typeof SplashRoute
  VisitsRoute: typeof VisitsRoute
  VisitsManagerRoute: typeof VisitsManagerRoute
  CandidatesRequestIdRoute: typeof CandidatesRequestIdRoute
  ChatsIdRoute: typeof ChatsIdRoute
  ExploreIdRoute: typeof ExploreIdRoute
  ExploreMapaRoute: typeof ExploreMapaRoute
  FeedbackMatchIdRoute: typeof FeedbackMatchIdRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  MyListingsNewRoute: typeof MyListingsNewRoute
  CandidatesIndexRoute: typeof CandidatesIndexRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  MyListingsIndexRoute: typeof MyListingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visits-manager': {
      id: '/visits-manager'
      path: '/visits-manager'
      fullPath: '/visits-manager'
      preLoaderRoute: typeof VisitsManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits': {
      id: '/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof VisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-ti': {
      id: '/para-ti'
      path: '/para-ti'
      fullPath: '/para-ti'
      preLoaderRoute: typeof ParaTiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests': {
      id: '/interests'
      path: '/interests'
      fullPath: '/interests'
      preLoaderRoute: typeof InterestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-listings/': {
      id: '/my-listings/'
      path: '/my-listings'
      fullPath: '/my-listings/'
      preLoaderRoute: typeof MyListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/': {
      id: '/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/': {
      id: '/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof CandidatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/score': {
      id: '/profile/score'
      path: '/score'
      fullPath: '/profile/score'
      preLoaderRoute: typeof ProfileScoreRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/my-listings/new': {
      id: '/my-listings/new'
      path: '/my-listings/new'
      fullPath: '/my-listings/new'
      preLoaderRoute: typeof MyListingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$matchId': {
      id: '/feedback/$matchId'
      path: '/feedback/$matchId'
      fullPath: '/feedback/$matchId'
      preLoaderRoute: typeof FeedbackMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/mapa': {
      id: '/explore/mapa'
      path: '/explore/mapa'
      fullPath: '/explore/mapa'
      preLoaderRoute: typeof ExploreMapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$id': {
      id: '/explore/$id'
      path: '/explore/$id'
      fullPath: '/explore/$id'
      preLoaderRoute: typeof ExploreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/$id': {
      id: '/chats/$id'
      path: '/chats/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof ChatsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/$requestId': {
      id: '/candidates/$requestId'
      path: '/candidates/$requestId'
      fullPath: '/candidates/$requestId'
      preLoaderRoute: typeof CandidatesRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteChildren {
  ProfileScoreRoute: typeof ProfileScoreRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileScoreRoute: ProfileScoreRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DashboardRoute: DashboardRoute,
  FavoritesRoute: FavoritesRoute,
  HelpRoute: HelpRoute,
  InboxRoute: InboxRoute,
  InterestsRoute: InterestsRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ParaTiRoute: ParaTiRoute,
  PreferencesRoute: PreferencesRoute,
  ProfileRoute: ProfileRouteWithChildren,
  PublishRoute: PublishRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoomsRoute: RoomsRoute,
  SettingsRoute: SettingsRoute,
  SplashRoute: SplashRoute,
  VisitsRoute: VisitsRoute,
  VisitsManagerRoute: VisitsManagerRoute,
  CandidatesRequestIdRoute: CandidatesRequestIdRoute,
  ChatsIdRoute: ChatsIdRoute,
  ExploreIdRoute: ExploreIdRoute,
  ExploreMapaRoute: ExploreMapaRoute,
  FeedbackMatchIdRoute: FeedbackMatchIdRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  MyListingsNewRoute: MyListingsNewRoute,
  CandidatesIndexRoute: CandidatesIndexRoute,
  ChatsIndexRoute: ChatsIndexRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  MyListingsIndexRoute: MyListingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
